### ISSUE TITLE
Push it to Maven Central

### ISSUE THREAD

**Issue by tchemit** [ravn/cajo#1]
Hi Ravn,

We are also using cajo in our project. It would be great if at last this project goes to Maven Central.

I have already do this job for others projects, I can help so far.

Are you ok with that? If so let me know, I will start to work on it.

thanks,

tony.

**Comment by ravn** [comment]
It turned out that John Catherino was ill and later died.  http://www.legacy.com/obituaries/freep/obituary.aspx?pid=179617006

**Comment by steffen-fissler** [comment]
Hi @ravn,

happy to see that you update this even after 10 years, thanks!

An contributor of ours wanted to update from 1.135 to 1.168 (https://mvnrepository.com/artifact/gnu.cajo/cajo/1.168 ) or later because of a security vulnerability detected with 1.135 (https://www.cve.org/CVERecord?id=CVE-2021-4277 (not sure why tho, I could not see any connection on a quick look)).

1.168 does not show an existing .jar anymore in the mvn repository.

So I tried to _mvn clean package_ your `master branch`.

I fail currently and got the below error.

```
Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile: java.lang.NoSuchMethodError: 'void org.codehaus.plexus.compiler.eclipse.EclipseJavaCompiler.logCompiling(java.lang.String[], org.codehaus.plexus.compiler.CompilerConfiguration)'
```

Does _mvn clean package_ currently work for you? If yes, then the issue there sits in front of my screen.

Either way, if you would consider providing any `.jar`, such a release either here or on mvncentral would be greatly appreciated.

Best regards
Steffen

**Comment by ravn** [comment]
Hi @steffen-fissler 

Dependabot had a few pull requests.  After applying them,  `mvn clean package` worked on my machine which runs Maven 3.8.4 with Java 18 (Azul) on MacOS 13.4.  Note that the Eclipse compiler is used instead of javac to stay compatible with Java 1.2. 

I do not use this project for anything these days, but I did on a daily basis a decade ago so I would like to keep it useful to others abeit with a minimum amount of effort on my side.   If you actually use this, feel free to submit patches or fork.  I currently do not have the time to do or interest in doing the testing and final polishing I consider appropriate for a Maven Central release.  I would strongly consider adding Github Actions, though.

It appears that http://nexus.nuiton.org/nexus/content/repositories/thirdparty/gnu/cajo/cajo/1.168/ is still live so using this repository in addition to Maven Central might be the simplest if your contributor just need a quick solution.

**Comment by steffen-fissler** [comment]
Dear @ravn 

thanks for the details and the link! cajo-1.168 does not solve the issue. We will probably not pursue this further, as it seems to be managable for now.

Sorry that we will not provide further effort here. :) 

Have a good day and thanks again for all the work!
